"""Create user table

Revision ID: 23126b364d71
Revises: 
Create Date: 2024-10-24 20:26:24.630397

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '23126b364d71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transporter_expense')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('username')

    op.drop_table('users')
    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('salary',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['license_number'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('withdrawal')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.add_column(sa.Column('withdrawal', mysql.FLOAT(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('salary',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.drop_column('user_id')

    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('theme', mysql.VARCHAR(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=True)

    op.create_table('transporter_expense',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('trip_from', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('trip_to', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('income', mysql.FLOAT(), nullable=False),
    sa.Column('expense', mysql.FLOAT(), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='transporter_expense_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
